# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: 'macOS-latest'

steps:

- script: yarn install
  displayName: 'run yarn install'

- script: yarn ios
  displayName: 'run yarn ios'